### ISSUE TITLE
As a trainer I want to define a last signup date

### ISSUE THREAD

**Issue by piamanns** [ohtutraininghub/traininghub#156]
### Task list:
- #161 

### Acceptance criteria:
- [x] An admin or a trainer can add a last date to enroll for a course
- [x] It is not possible for a trainee to enroll for a course after the enrollment deadline
- [x] Adding an enrollment deadline for a course is optional; if there is no last enrollment date, trainees can sign up for a course at any point
