### ISSUE TITLE
As a trainer I want to define a last cancel date

### ISSUE THREAD

**Issue by piamanns** [ohtutraininghub/traininghub#157]
### Task list:
- #162 

### Acceptance criteria:
- [ ] An admin or a trainer can add a last date when cancelling enrollment is still allowed for a course
- [ ] A trainee that has enrolled for a course can no longer cancel their enrollment after the cancellation deadline
- [ ] The field is optional; if no last cancellation date exists, it is possible to cancel ones enrollment for a course at any time
