### ISSUE TITLE
As a trainer, I want to be able to list all people who have signed up for my course

### ISSUE THREAD

**Issue by piamanns** [ohtutraininghub/traininghub#22]
### Task list: 
- [x] #195 
- [x] Implement unit tests
- [x] Implement e2e-tests

### Acceptance criteria
- [x] Admins and trainers should be able to see a list with all students enrolled in a course. The list contains the names of the students.
- [x] A user with a trainee role should not not be able to view the list
